version: "3"
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  server:
    build: ./
    environment:
      MONGODB_HOST: mongodb
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongodb